repos:
-   repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
      stages: [commit]
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      stages: [commit]
      args: [intake_hive]
    - id: flake8
      name: flake8
      language: system
      entry: flake8
      types: [python]
      stages: [commit]
      # TODO(talebz): Remove when this issue is resolve https://gitlab.com/pycqa/flake8/issues/450
      exclude: >
        (?x)^(
            uranium|
            docs/conf.py
        )$
    - id: pytest
      name: pytest
      language: system
      entry: pytest
      pass_filenames: false
      stages: [commit]
      args: [intake_hive, --cov=intake_hive, --cov-config=setup.cfg, --cov-report=term, --cov-report=html]
