language: python
matrix:
  include:
    - python: 3.6
      jdk:
        - oraclejdk8
      sudo: false
      env:
        - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
        - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
before_install:
  - pip install --upgrade pip
  - pip install poetry
install:
  - poetry install
  - pip install coveralls
script:
  - poetry run flake8 intake_hive
  - poetry run pytest intake_hive
after_success:
    coveralls
